### ISSUE TITLE
Generate IDs for relations

### ISSUE THREAD

**Issue by paulinaschenk** [ontology-tools/onto-spread-ed#27]
There seems to be an issue with adding with adding new relations to the folder "BCIO_Upper_Rels.xlsx". Several relations need to be added for the Behaviour Ontology. While this was not an issue for relations reused from other ontologies (e.g., "starts" from the Relation Ontology with the URI: RO:0002223), other relations that are specific to the BCIO could not be added. When trying to add such relations, the error "REPO not found - 'Label' is not in list" came up.
[Relations that need to be added to BCIO_Upper_Rels.xlsx](https://github.com/jannahastings/onto-spread-ed/files/13207414/Relations.that.need.to.be.added.to.BCIO_Upper_Rels.xlsx)

**Comment by b-gehrke** [comment]
The error comes from the ID field being empty. Currently, the editor does not generate IDs for new relations automatically. 

Please fill in the IDs manually until this is fixed. The IDs should follow the format `BCIOR:######` (note the *R*) and the next free ID (at the moment) is `BCIOR:000009`.

**Comment by paulinaschenk** [comment]
Thank you for the recommendation! As manual ID generation might result in duplicates, would there be a way to generate automatic IDs in the spreadsheet for relations?
