### ISSUE TITLE
Error when trying to record numbers under "LSR no." in the GMHO spreadsheets

### ISSUE THREAD

**Issue by paulinaschenk** [ontology-tools/onto-spread-ed#40]
For classes in the GMHO, we need to record which LSRs the classes are relevant to (e.g., LSR 1, 2 etc.), but the column in the spreadsheets labelled as 'LSR no.' does not seem to allow me to record numbers. The following error comes up: "REPO not found - Cannot convert  {'': '3'} to Excel".

**Comment by b-gehrke** [comment]
Fixed with 2278183.
